.TH "PP" "1" "April 2020" "preprocessor" "pp manual"
.SH NAME
pp \- the POSIX sh text preprocessor
.SH SYNOPSIS
.B pp
[\fB\-v\fR|\fB\-\-version\fR] 
[\fB\-h\fR|\fB\-\-help\fR]
.br
.B pp
.IR input-file
.SH DESCRIPTION
.B pp
preprocesses text files, expanding macros written in shell. This can be used before compiling to its final format (e.g. piping into pandoc). The marked shell commands (see \fISYNTAX\fR) are replaced by their evaluated output when written to the standard output. The input text can be read from standard input or from a file as the first argument.
.PP
.B pp
is also written exclusively in POSIX sh so there are no dependencies.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print usage information and exit.
.TP
.BR \-v ", " \-\-version
Print version information and exit.
.SH SYNTAX
.SS !!
.PP
Shell commands to be processed are on lines beginning immediately with two exclamation marks \fB!!\fR. When \fBpp\fR is run on the file the text following the \fB!!\fR and before a newline is evaluated in \fIsh\fR. Therefore:
.IP
.nf
\f[C]
foo
!! echo "Insert Text"
bar
\f[R]
.PP
becomes,
.IP
\f[C]
foo
Insert Text
bar
\f[R]
.fi
.SS $FILE, $line and $ln
.PP
There are three useful variables for writing these macros. \fB$FILE\fR is the name of the file relative to the users \fBPWD\fR, the basename can be found with `\fI${FILE##*/}\fR'. This is only readable when not receiving text from standard input. \fB$line\fR is the contents of the local line with \fB!!\fR and leading whitespace removed. \fB$ln\fR is the local line number. These can be used for more complex operations and file manipulation.
.IP
.nf
\f[C]
foo
!! cat "$FILE"
bar
\f[R]
.PP
becomes,
.IP
\f[C]
foo
foo
!! cat "$FILE"
bar
bar
\f[R]
.fi
.SH EXAMPLES 
.PP 
To import an html body, \fIbody.txt\fR, and title an html document with the name of the file \fIhome.html\fR, the input file would look like:
.IP
.nf
\f[C]
<title>
!! echo "${FILE%%.*}"
</title>
<h1>Hello World!</h1>
<body>
!! cat "/path/to/body.txt"
</body>
\f[R]
.PP
running `\fBpp\fR home.html' gives the output,
.IP
\f[C]
<title>
home
</title>
<h1>Hello World!</h1>
<body>
Lorem ipsum,
dolor sit amet.
</body>
\f[R]
.fi
.SH AUTHOR
Joe Jenne <\fIjhjn.xyz\fR>
